"""Render a triage report as colored terminal text, JSON, or HTML."""
import json

C = {"red": "\033[31m", "yel": "\033[33m", "grn": "\033[32m", "cya": "\033[36m",
     "dim": "\033[90m", "bold": "\033[1m", "rst": "\033[0m"}
_VC = {"MALICIOUS": "red", "SUSPICIOUS": "yel", "CLEAN": "grn", "UNKNOWN": "dim"}
_SV = {"malicious": "red", "suspicious": "yel", "clean": "grn", "info": "cya",
       "no-key": "dim", "error": "dim"}


def _bar(score, width=24):
    fill = int(round(score / 100 * width))
    return "#" * fill + "-" * (width - fill)


def render_terminal(rep, color=True):
    def c(name, s):
        return (C[name] + s + C["rst"]) if color else s
    out = []
    vc = _VC.get(rep["verdict"], "dim")
    out.append("")
    out.append("  " + c("bold", "ThreatTriage") + "  ::  " + rep["indicator"] + c("dim", "  [%s]" % rep["type"]))
    out.append("  " + "-" * 60)
    out.append("  Verdict:  " + c(vc, c("bold", rep["verdict"])) +
               "    Risk: " + c(vc, "%3d/100" % rep["score"]) + "  [" + c(vc, _bar(rep["score"])) + "]")
    if rep.get("flagged_by"):
        out.append("  " + c("dim", "Flagged by: " + ", ".join(rep["flagged_by"])))
    if rep.get("note"):
        out.append("  " + c("dim", rep["note"]))
    out.append("  " + "-" * 60)
    for r in rep["results"]:
        sv = _SV.get(r["verdict"], "dim")
        if not r["available"]:
            out.append("  " + c("dim", "  -  %-22s %s" % (r["source"], r["summary"])))
        else:
            tag = ("%3d" % r["score"]) if r["score"] is not None else " - "
            out.append("  " + c(sv, "  *") + "  %-22s " % r["source"] + c(sv, "[%s] " % tag) + r["summary"])
    out.append("")
    return "\n".join(out)


def render_json(rep):
    return json.dumps(rep, indent=2)


def render_html(rep):
    vcol = {"MALICIOUS": "#f87171", "SUSPICIOUS": "#fbbf24", "CLEAN": "#34d399", "UNKNOWN": "#647772"}
    scol = {"malicious": "#f87171", "suspicious": "#fbbf24", "clean": "#34d399", "info": "#2dd4bf"}
    rows = ""
    for r in rep["results"]:
        col = scol.get(r["verdict"], "#647772") if r["available"] else "#647772"
        sc = r["score"] if (r["available"] and r["score"] is not None) else "-"
        rows += ("<tr><td style='color:%s;font-weight:700'>%s</td><td>%s</td>"
                 "<td>%s</td><td>%s</td></tr>") % (col, r["source"],
                 r["verdict"], sc, _esc(r["summary"]))
    vc = vcol.get(rep["verdict"], "#647772")
    return """<!DOCTYPE html><html><head><meta charset="utf-8"><title>ThreatTriage - %s</title>
<style>body{background:#0a0f0d;color:#d5e3df;font-family:'Segoe UI',sans-serif;max-width:780px;margin:30px auto;padding:0 20px}
h1{font-family:'Chakra Petch',sans-serif} .v{color:%s;font-weight:800;font-size:34px}
table{width:100%%;border-collapse:collapse;margin-top:16px} th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #1e2a28;font-size:14px}
th{color:#647772;text-transform:uppercase;font-size:11px;letter-spacing:.5px} .ind{font-family:monospace;color:#2dd4bf}</style></head>
<body><h1>ThreatTriage</h1><p class="ind">%s &nbsp; [%s]</p>
<div class="v">%s &middot; %d/100</div>
<table><tr><th>Source</th><th>Verdict</th><th>Score</th><th>Summary</th></tr>%s</table>
<p style="color:#647772;font-size:12px;margin-top:20px">Generated by ThreatTriage - local IOC enrichment, no cloud.</p>
</body></html>""" % (_esc(rep["indicator"]), vc, _esc(rep["indicator"]), rep["type"],
                     rep["verdict"], rep["score"], rows)


def _esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
